/*
 * go-openapi-generator-example
 *
 * Example of REST API. Includes such things as MongoDB, slog, gorilla mux etc... Some kind of a sample project API for educational purposes.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type ApiError struct {

	// Error message
	Message string `json:"message"`
}

// AssertApiErrorRequired checks if the required fields are not zero-ed
func AssertApiErrorRequired(obj ApiError) error {
	elements := map[string]interface{}{
		"message": obj.Message,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertApiErrorConstraints checks if the values respects the defined constraints
func AssertApiErrorConstraints(obj ApiError) error {
	return nil
}
