/*
 * go-openapi-generator-example
 *
 * Example of REST API. Includes such things as MongoDB, slog, gorilla mux etc... Some kind of a sample project API for educational purposes.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"log"
	"net/http"
	"time"

	"github.com/google/uuid"
)

// this thing is heavily rebuild and I don't think it's a good idea
// if you want more control on logging use other library or framework to generate
type RequestData struct {
	ID     string
	Method string
	Path   string
}

type reqDataCtxKey struct{}

func RequestDataFromContext(ctx context.Context) RequestData {
	reqData, _ := ctx.Value(reqDataCtxKey{}).(RequestData)

	return reqData
}

func Logger(inner http.Handler, name string) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		start := time.Now()

		inner.ServeHTTP(w, r.WithContext(context.WithValue(r.Context(), reqDataCtxKey{}, RequestData{
			ID:     uuid.NewString(),
			Method: r.Method,
			Path:   r.URL.Path,
		})))

		log.Printf(
			"%s %s %s %s",
			r.Method,
			r.RequestURI,
			name,
			time.Since(start),
		)
	})
}
