/*
 * go-openapi-generator-example
 *
 * Example of REST API. Includes such things as MongoDB, slog, gorilla mux etc... Some kind of a sample project API for educational purposes.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type CreatedItem struct {

	// New ID of created object
	Id string `json:"id"`
}

// AssertCreatedItemRequired checks if the required fields are not zero-ed
func AssertCreatedItemRequired(obj CreatedItem) error {
	elements := map[string]interface{}{
		"id": obj.Id,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertCreatedItemConstraints checks if the values respects the defined constraints
func AssertCreatedItemConstraints(obj CreatedItem) error {
	return nil
}
